# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

import os
import requests
from typing import List, Dict
from utils import normalise_date, now_utc

def fetch_newsapi_articles(
    keywords: List[str],
    max_items: int = 100,
    language: str = "fr"
) -> List[Dict]:

    #Сбор статей из NewsAPI.org по заданным ключевым словам.

    api_key = os.getenv("NEWSAPI_KEY")
    if not api_key:
        raise RuntimeError("NEWSAPI_KEY not set")
    url = "https://newsapi.org/v2/everything"
    articles: List[Dict] = []
    for kw in keywords:
        params = {
            "q": kw,
            "language": language,
            "pageSize": max_items,
            "sortBy": "publishedAt",
            "apiKey": api_key,
        }
        resp = requests.get(url, params=params, timeout=15)
        resp.raise_for_status()
        data = resp.json().get("articles", [])
        for art in data:
            articles.append({
                "source": art.get("source", {}).get("name"),
                "title": art.get("title"),
                "content": art.get("description") or art.get("content"),
                "published": normalise_date(art.get("publishedAt")),
                "url": art.get("url"),
                "author": art.get("author"),
            })
    print(f"[{now_utc()}] Слов получено через NewsAPI: {len(articles)}")
    return articles
