# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

import os
import sys
import subprocess

REPO_URL = "https://github.com/vkalinovski/RSS_Project.git"
LOCAL_DIR = "RSS_Project"

# Клонируем репозиторий
if not os.path.isdir(LOCAL_DIR):
    print(f"Cloning repository from {REPO_URL}...")
    subprocess.run(["git", "clone", REPO_URL, LOCAL_DIR], check=True)

# зависимости
requirements = os.path.join(LOCAL_DIR, "requirements.txt")
if os.path.exists(requirements):
    print("Installing dependencies...")
    subprocess.run([sys.executable, "-m", "pip", "install", "-r", requirements], check=True)

# Добавляем папку с модулями в путь импорта
sys.path.insert(0, os.path.abspath(LOCAL_DIR))

# Импорт модулей из клонированного репозитория
from rss_feeds import RSS_FEEDS
from api_fetcher import fetch_newsapi_articles
from rss import fetch_rss_articles
from database_utils import create_database, save_news_to_db
from sentiment_analysis import analyze_sentiment
from analyze import (
    build_timeseries,
    plot1_timeseries, plot2_bar_total, plot3_rolling, plot4_monthly,
    plot5_pie_sources, plot6_weekday, plot7_top_days,
    plot8_cumulative, plot9_ratio, plot10_correlation
)
from utils import now_utc

# Конфигурация
KEYWORDS   = ["Emmanuel Macron", "Marine Le Pen"]
MAX_ITEMS  = 200
OUT_DIR    = "/content/drive/MyDrive/test"

# Основная логика
import pandas as pd

def one_cycle():
    print(f"[{now_utc()}] Запуск цикла: сбор → анализ → сохранение")

    # Создаём/обновляем БД
    create_database()

    # Сбор новостей
    rss_news = fetch_rss_articles(MAX_ITEMS)
    api_news = fetch_newsapi_articles(KEYWORDS, MAX_ITEMS)
    all_news = rss_news + api_news

    # Фильтрация по политическим деятелям
    macron = [n for n in all_news if "Emmanuel Macron" in (n.get('content') or "")]
    lepen  = [n for n in all_news if "Marine Le Pen"  in (n.get('content') or "")]

    # Сохранение в базу
    save_news_to_db(macron, "Emmanuel Macron")
    save_news_to_db(lepen,  "Marine Le Pen")

    # Тональный анализ
    combined = macron + lepen
    sentimented = analyze_sentiment(combined)

    # Временной ряд
    df = pd.DataFrame(sentimented)
    ts = build_timeseries(df)
    ts.to_csv(os.path.join(OUT_DIR, "timeseries.csv"), index=True)

    # 10 графиков глубокого анализа
    plot1_timeseries(ts, OUT_DIR)
    plot2_bar_total(ts, OUT_DIR)
    plot3_rolling(ts, OUT_DIR)
    plot4_monthly(ts, OUT_DIR)
    plot5_pie_sources(df, OUT_DIR)
    plot6_weekday(ts, OUT_DIR)
    plot7_top_days(ts, OUT_DIR)
    plot8_cumulative(ts, OUT_DIR)
    plot9_ratio(ts, OUT_DIR)
    plot10_correlation(ts, OUT_DIR)

    print(f"[{now_utc()}] Цикл завершён. Результаты сохранены в {OUT_DIR}")

if __name__ == '__main__':
    one_cycle()