# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

import feedparser
from typing import List, Dict
from .rss_feeds import RSS_FEEDS
from .utils import normalise_date, now_utc

def fetch_rss_articles(max_items: int = 100) -> List[Dict]:
    #Сбор статей из RSS-лент, определённых в rss_feeds.py
    articles: List[Dict] = []
    for name, url in RSS_FEEDS.items():
        feed = feedparser.parse(url)
        for entry in feed.entries[:max_items]:
            articles.append({
                "source": name,
                "title": entry.get("title"),
                "content": entry.get("summary"),
                "published": normalise_date(entry.get("published")),
                "url": entry.get("link"),
                "author": entry.get("author"),
            })
    print(f"[{now_utc()}] Слов получено из RSS: {len(articles)}")
    return articles