# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

RSS_FEEDS = {
    "Le Monde Politique": "https://www.lemonde.fr/politique/rss_full.xml",
    "Reuters World Politics": "https://www.reuters.com/rssFeed/politicsNews",
    "Politico Europe": "https://www.politico.eu/feed/",
    "France Info Politique": "https://www.francetvinfo.fr/politique/rss.xml",
    "Le Figaro Politique": "http://www.lefigaro.fr/rss/figaro_politique.xml",
    "Libération Politique": "https://www.liberation.fr/rss/politique/",
    "RFI Français": "http://www.rfi.fr/fr/rss",
    "Le Parisien Politique": "https://www.leparisien.fr/politique/rss.xml",
    "L'Express Politique": "https://www.lexpress.fr/actualite/monde/europe/politique/rss.xml",
    "Euronews Politique": "https://www.euronews.com/rss?level=theme&name=politics",
}