# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

from transformers import pipeline
from typing import List, Dict

_sentiment = pipeline('sentiment-analysis')

def analyze_sentiment(news: List[Dict]) -> List[Dict]:
    # Добавляет поле sentiment: positive/negative для каждой статьи.

    texts = [art.get('content') or art.get('title','') for art in news]
    results = _sentiment(texts)
    for art, res in zip(news, results):
        art['sentiment'] = res.get('label')
    return news