# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_j7EBQXocwJpJVWDYcIBhyr2w0ZG75C
"""

import datetime as dt

def now_utc() -> str:
    return dt.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S") #Текущее время UTC в формате строки

def normalise_date(date_str: str | None) -> str: # Приводим дату публикации к YYYY-MM-DD

    if not date_str:
        return dt.datetime.utcnow().strftime("%Y-%m-%d")
    for fmt in ("%a, %d %b %Y %H:%M:%S %Z", "%Y-%m-%dT%H:%M:%SZ", "%Y-%m-%d"):
        try:
            return dt.datetime.strptime(date_str[:25], fmt).strftime("%Y-%m-%d")
        except Exception:
            continue
    return dt.datetime.utcnow().strftime("%Y-%m-%d")